# Generated by Django 5.0.4 on 2024-04-16 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('car_model_id', models.IntegerField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('number_of_owners', models.IntegerField()),
                ('registration_number', models.CharField(max_length=255, unique=True)),
                ('manufacture_year', models.IntegerField()),
                ('number_of_doors', models.IntegerField(default=5)),
                ('mileage', models.IntegerField()),
                ('car_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_app.carmodel')),
            ],
        ),
    ]
