# Generated by Django 5.0.4 on 2024-04-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_model_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
