# Generated by Django 5.0.4 on 2024-04-16 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('advertisement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('advertisement_date', models.DateField()),
                ('car_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars_app.car')),
                ('seller_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.appuser')),
            ],
        ),
    ]
