# Generated by Django 5.0.4 on 2024-04-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='advertisement_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
